### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by empeje** [devillexio/docker-firebase#10]
Hi, @devillexio I fan of your docker image. I use it for my agency. Wondering if you could have some sort of versioning on the docker image tag you publish on Docker Hub.

Thank you for providing us with out of the box docker-firebase 🎉

**Comment by devilleweppenaar** [comment]
Hi @empeje. I'm happy you find it useful. 🙂 

Not sure what you have in mind in terms of tagging. I chose the LTS with the idea that it should be fairly stable.

I did notice though that the images haven't been updated for 4 months. That's mainly because of the Zapier integration I use to trigger the weekly builds broke. I manually triggered a build now and also fixed the Zapier integration.

**Comment by empeje** [comment]
I'm thinking that you can have your own versioning system, such that in the future it didn't break our CI system unexpectedly. However, if we're following the LTS versioning, the weekly build is sufficient I guess.

Thanks for the great work 🎉

**Comment by devilleweppenaar** [comment]
Pretty much the building of the images is taken care of by Docker Hub and a weekly endpoint call from Zapier. Keeping with the LTS base image should keep it fairly stable. I also fix any issues that come up, since we use it daily.

Feel free to report any issues, but so far it seems to be working okay. 🙂
